(TeX-add-style-hook "master"
 (lambda ()
    (LaTeX-add-bibliographies
     "math")
    (TeX-run-style-hooks
     "geometry"
     "outer=2cm"
     "inner=3cm"
     "emptypage"
     "setspace"
     "booktabs"
     "url"
     "graphics"
     "calligra"
     "mathenv"
     "makeidx"
     ""
     "latex2e"
     "art11"
     "article"
     "twoside"
     "a4paper"
     "11pt"
     "../Config/math"
     "titlepage"
     "dedication"
     "statutorydeclaration"
     "acknowledgement"
     "prelim"
     "combcons"
     "mdsmainconj"
     "generichyperplanearr"
     "reedsolomon"
     "mdsmainconjnleqp"
     "mdsmainconjknesgraph"
     "summary")))

