(TeX-add-style-hook "RAspicker"
 (lambda ()
    (TeX-add-symbols
     "imm"
     "val"
     "mem"
     "ls"
     "rs"
     "rsa"
     "incr"
     "concat"
     "iu"
     "imme")
    (TeX-run-style-hooks
     "float"
     "graphicx"
     "svg"
     "parskip"
     "babel"
     "ngerman"
     "titlesec"
     "blindtext"
     "geometry"
     "margin=0.5cm"
     "multicol"
     "amssymb"
     "amsfonts"
     "amsmath"
     ""
     "inputenc"
     "utf8"
     "latex2e"
     "art10"
     "article"
     "a4paper"
     "8pt"
     "../MathFiles/math")))

