(TeX-add-style-hook "master"
 (lambda ()
    (TeX-run-style-hooks
     "geometry"
     "outer=2cm"
     "inner=3cm"
     "emptypage"
     "setspace"
     "booktabs"
     "url"
     "graphics"
     "calligra"
     "mathenv"
     "makeidx"
     ""
     "latex2e"
     "art11"
     "article"
     "twoside"
     "a4paper"
     "11pt"
     "../Config/math"
     "titlepage"
     "dedication"
     "statutorydeclaration")))

